# Generated by Django 3.0.8 on 2020-07-17 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpics',
            name='id',
        ),
        migrations.AddField(
            model_name='userpics',
            name='hobby',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userpics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
