# Generated by Django 3.0.8 on 2020-07-17 01:38

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200717_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpics',
            name='user',
            field=models.FloatField(primary_key=True, serialize=False, verbose_name=django.contrib.auth.models.User),
        ),
    ]
