# Generated by Django 3.0.8 on 2020-07-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200717_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpics',
            name='user',
        ),
        migrations.AddField(
            model_name='userpics',
            name='user_id',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
