# Generated by Django 3.0.8 on 2020-07-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200720_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpics',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userpics',
            name='user',
            field=models.CharField(default=2, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
